CREATE TABLE TB_PAYMENT (
  PAYMENT_SEQ INT(10) NOT NULL AUTO_INCREMENT,
  PAYMENT_KEY varchar(4),
  RECEIVE_WALLET varchar(200),
  REFUND_WALLET varchar(200),
  TOTAL_AMOUNT DECIMAL(18,5),
  STATUS varchar(20) CHECK (STATUS IN ('UNPAID','PAID','REFUND','CANCEL')),

  PRIMARY KEY(PAYMENT_SEQ)
);
