CREATE TABLE TB_ROOM (
  ROOM_SEQ INT(10) NOT NULL AUTO_INCREMENT,
  ROOM_NAME varchar(50),
  ROOM_URL varchar(200),
  ROOM_DESC varchar(100),
  ROOM_SPEC varchar(200),
  ROOM_ALT varchar(100),
  ROOM_PRICE DECIMAL(8,5),
  PRIMARY KEY(ROOM_SEQ)
);
